
services:
  mission-control-simplified:
    build:
      context: ./services/mission-control-simplified
      dockerfile: Dockerfile
    container_name: mission-control-simplified
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
    restart: unless-stopped
    volumes:
      - ./services/mission-control-simplified/public:/app/public
    networks:
      - alfred-network
    depends_on:
      - social-intel
      - financial-tax
      - legal-compliance
